### ISSUE TITLE
The download URL on sympa.org has changed !

### ISSUE THREAD

**Issue by ParleurA** [YunoHost-Apps/sympa_ynh#3]
Hello !

This script still tries to download sympa from this URL https://www.sympa.org/distribution/sympa-6.2.16.tar.gz

However, thus version of sympa is a little outdated, and the fila has changed its URL.

The new one is : https://www.sympa.org/distribution/old/sympa-6.2.16.tar.gz

Would you please make this little change (or upgrade to the last Sympa version) ? :)

**Comment by alexAubin** [comment]
Sould be fixed by #5 (Sorry I didnt even realize you opened those issues :s )
